/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatopilha.view;

import automatopilha.dto.Automato;
import automatopilha.dto.Estado;
import automatopilha.dto.TableAlfabetoModel;
import automatopilha.dto.TableEstadosModel;
import automatopilha.dto.TableSimbolosPilhaModel;
import automatopilha.dto.TableTransicoesModel;
import automatopilha.dto.Transicao;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lucastaise
 */
public class Tela extends javax.swing.JFrame {

    
    TableEstadosModel modelEstados = new TableEstadosModel();
    TableAlfabetoModel modelAlfabeto = new TableAlfabetoModel();
    TableSimbolosPilhaModel modelSimbolosPilha = new TableSimbolosPilhaModel();
    TableTransicoesModel modelTransicoes = new TableTransicoesModel();
    Automato automato = new Automato();
    
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        tabelaEstados.setModel(modelEstados);
        tabelaAlfabeto.setModel(modelAlfabeto);
        tabelaSimbolosPilha.setModel(modelSimbolosPilha);
        tabelaTransicoes.setModel(modelTransicoes);
        comboEstadoInicial.addItem("Selecione um estado");
        comboSimboloInicialPilha.addItem("Selecione um item");
        comboEstadoAtualTransicao.addItem("Selecione um item");
        comboEntradaTransicao.addItem("Selecione um item");
        comboValorPilhaTransicao.addItem("Selecione um item");
        comboValorEntradaPilhaTransicao.addItem("Selecione um item");
        comboProximoEstadoTransicao.addItem("Selecione um item");
        labelResultado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEstados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        textNomeEstado = new javax.swing.JTextField();
        checkEhFinal = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        btnAdicionarEstado = new javax.swing.JButton();
        btnRemoverEstado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaAlfabeto = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        textValorAlfabeto = new javax.swing.JTextField();
        btnSalvarAlfabeto = new javax.swing.JButton();
        btnRemoverAlfabeto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaSimbolosPilha = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnSalvarSimboloPilha = new javax.swing.JButton();
        btnRemoverSimboloPilha = new javax.swing.JButton();
        txtSimboloPilha = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboEstadoInicial = new javax.swing.JComboBox<>();
        comboSimboloInicialPilha = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaTransicoes = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboEstadoAtualTransicao = new javax.swing.JComboBox<>();
        comboEntradaTransicao = new javax.swing.JComboBox<>();
        comboValorPilhaTransicao = new javax.swing.JComboBox<>();
        comboValorEntradaPilhaTransicao = new javax.swing.JComboBox<>();
        comboProximoEstadoTransicao = new javax.swing.JComboBox<>();
        btnAdicionarTransicao = new javax.swing.JButton();
        btnRemoverTransicao = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        textPalavra = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaAnalise = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        btnProcessar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook L", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Autômato de Pilha");

        tabelaEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEstadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaEstados);

        jLabel2.setText("Nome");

        checkEhFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEhFinalActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado final?");

        btnAdicionarEstado.setText("Salvar");
        btnAdicionarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEstadoActionPerformed(evt);
            }
        });

        btnRemoverEstado.setText("Remover");
        btnRemoverEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkEhFinal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRemoverEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnAdicionarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkEhFinal)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarEstado)
                    .addComponent(btnRemoverEstado))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estados", jPanel1);

        tabelaAlfabeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaAlfabeto);

        jLabel4.setText("Valor");

        textValorAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorAlfabetoActionPerformed(evt);
            }
        });

        btnSalvarAlfabeto.setText("Salvar");
        btnSalvarAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlfabetoActionPerformed(evt);
            }
        });

        btnRemoverAlfabeto.setText("Remover");
        btnRemoverAlfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverAlfabetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textValorAlfabeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addComponent(btnRemoverAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textValorAlfabeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAlfabeto)
                    .addComponent(btnRemoverAlfabeto))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alfabeto", jPanel2);

        tabelaSimbolosPilha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaSimbolosPilha);

        jLabel5.setText("Valor");

        btnSalvarSimboloPilha.setText("Salvar");
        btnSalvarSimboloPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarSimboloPilhaActionPerformed(evt);
            }
        });

        btnRemoverSimboloPilha.setText("Remover");
        btnRemoverSimboloPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverSimboloPilhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSimboloPilha, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnRemoverSimboloPilha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarSimboloPilha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSimboloPilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarSimboloPilha)
                    .addComponent(btnRemoverSimboloPilha))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Símbolos Pilha", jPanel3);

        jLabel6.setText("Estado inicial");

        jLabel7.setText("Símbolo inicial da pilha");

        comboEstadoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboEstadoInicial, 0, 146, Short.MAX_VALUE)
                    .addComponent(comboSimboloInicialPilha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboEstadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSimboloInicialPilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Definições iniciais", jPanel4);

        tabelaTransicoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabelaTransicoes);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Estado atual");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Valor entrada");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Valor Pilha");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Valor Entrada Pilha");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Próximo Estado");

        btnAdicionarTransicao.setText("Adicionar");
        btnAdicionarTransicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTransicaoActionPerformed(evt);
            }
        });

        btnRemoverTransicao.setText("Remover");
        btnRemoverTransicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverTransicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboEstadoAtualTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEntradaTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboValorPilhaTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboValorEntradaPilhaTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboProximoEstadoTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoverTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionarTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboEstadoAtualTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEntradaTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboValorPilhaTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboValorEntradaPilhaTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comboProximoEstadoTransicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarTransicao)
                    .addComponent(btnRemoverTransicao))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transições", jPanel5);

        jLabel13.setText("Palavra");

        areaAnalise.setColumns(20);
        areaAnalise.setRows(5);
        jScrollPane5.setViewportView(areaAnalise);

        jLabel14.setText("Análise");

        labelResultado.setBackground(new java.awt.Color(242, 240, 240));
        labelResultado.setFont(new java.awt.Font("Purisa", 3, 36)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(255, 18, 0));
        labelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultado.setText("Falhou");

        btnProcessar.setText("Processar");
        btnProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textPalavra, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcessar)
                        .addGap(41, 41, 41)))
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(textPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcessar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Executar", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkEhFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEhFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEhFinalActionPerformed

    private void btnAdicionarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEstadoActionPerformed
        // TODO add your handling code here:                
        Estado estadoExistente = automato.buscarEstadoPorNome(textNomeEstado.getText());
        if (estadoExistente == null){
            Estado estado = new Estado();
            estado.setNome(textNomeEstado.getText());
            estado.setEhFinal(checkEhFinal.isSelected());

            automato.addEstado(estado);
            modelEstados.addRow(estado);
            comboEstadoInicial.addItem(estado.getNome());
            comboEstadoAtualTransicao.addItem(estado.getNome());
            comboProximoEstadoTransicao.addItem(estado.getNome());
            textNomeEstado.setText("");
            checkEhFinal.setSelected(false);
        } else {
            JOptionPane.showMessageDialog(null, "Estado com nome "+textNomeEstado.getText()+" já existe!");
        }
        
        
    }//GEN-LAST:event_btnAdicionarEstadoActionPerformed

    private void btnRemoverEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverEstadoActionPerformed
        // TODO add your handling code here:
        
        if (tabelaEstados.getSelectedRow() != -1){
            automato.getEstados().remove(tabelaEstados.getSelectedRow());
            comboEstadoInicial.removeItemAt(tabelaEstados.getSelectedRow()+1);
            comboEstadoAtualTransicao.removeItemAt(tabelaEstados.getSelectedRow()+1);
            comboProximoEstadoTransicao.removeItemAt(tabelaEstados.getSelectedRow()+1);
            modelEstados.removeRow(tabelaEstados.getSelectedRow());
        }
        
    }//GEN-LAST:event_btnRemoverEstadoActionPerformed

    private void tabelaEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEstadosMouseClicked
        // TODO add your handling code here:
        Estado estado = modelEstados.getListaEstados().get(tabelaEstados.getSelectedRow());
        if (estado != null){
            textNomeEstado.setText(estado.getNome());
            checkEhFinal.setSelected(estado.isEhFinal());
        }
    }//GEN-LAST:event_tabelaEstadosMouseClicked

    private void textValorAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorAlfabetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorAlfabetoActionPerformed

    private void btnSalvarAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlfabetoActionPerformed
        // TODO add your handling code here:
        String valorExistente = automato.buscarAlfabetoPorValor(textValorAlfabeto.getText());
        if (valorExistente == null){
            automato.addAlfabeto(textValorAlfabeto.getText());
            modelAlfabeto.addRow(textValorAlfabeto.getText());  
            comboEntradaTransicao.addItem(textValorAlfabeto.getText());
            textValorAlfabeto.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Valor "+textValorAlfabeto.getText()+" já existe!");
        }
    }//GEN-LAST:event_btnSalvarAlfabetoActionPerformed

    private void btnRemoverAlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverAlfabetoActionPerformed
        // TODO add your handling code here:
        if (tabelaAlfabeto.getSelectedRow() != -1){
            automato.getAlfabeto().remove(tabelaAlfabeto.getSelectedRow());
            comboEntradaTransicao.removeItemAt(tabelaAlfabeto.getSelectedRow()+1);
            modelAlfabeto.removeRow(tabelaAlfabeto.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoverAlfabetoActionPerformed

    private void btnSalvarSimboloPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarSimboloPilhaActionPerformed
        // TODO add your handling code here:
        String valorExistente = automato.buscarSimboloPilhaPorValor(txtSimboloPilha.getText());
        if (valorExistente == null){
            automato.addAlfabetoPilha(txtSimboloPilha.getText());
            modelSimbolosPilha.addRow(txtSimboloPilha.getText());  
            comboSimboloInicialPilha.addItem(txtSimboloPilha.getText());
            comboValorPilhaTransicao.addItem(txtSimboloPilha.getText());
            comboValorEntradaPilhaTransicao.addItem(txtSimboloPilha.getText());
            txtSimboloPilha.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Valor "+txtSimboloPilha.getText()+" já existe!");
        }
    }//GEN-LAST:event_btnSalvarSimboloPilhaActionPerformed

    private void btnRemoverSimboloPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverSimboloPilhaActionPerformed
        // TODO add your handling code here:
        if (tabelaSimbolosPilha.getSelectedRow() != -1){
            automato.getAlfabetoPilha().remove(tabelaSimbolosPilha.getSelectedRow());
            comboSimboloInicialPilha.removeItemAt(tabelaSimbolosPilha.getSelectedRow()+1);
            comboValorPilhaTransicao.removeItemAt(tabelaSimbolosPilha.getSelectedRow()+1);
            comboValorEntradaPilhaTransicao.removeItemAt(tabelaSimbolosPilha.getSelectedRow()+1);
            modelSimbolosPilha.removeRow(tabelaSimbolosPilha.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoverSimboloPilhaActionPerformed

    private void btnAdicionarTransicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTransicaoActionPerformed
        // TODO add your handling code here:
        boolean ehValido = true;
        if (comboEstadoAtualTransicao.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Deve ser informado um estado atual para transição");
            ehValido = false;
        }
        if (comboValorPilhaTransicao.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Deve ser informado um valor atual da pilha para transição");
            ehValido = false;
        }        
        if (comboProximoEstadoTransicao.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Deve ser informado um próximo estado para transição");
            ehValido = false;
        }
        
        if (ehValido) {
            Estado estadoAtualTransicao = automato.buscarEstadoPorNome((String)comboEstadoAtualTransicao.getSelectedItem());
            Estado proximoEstadoTransicao = automato.buscarEstadoPorNome((String)comboProximoEstadoTransicao.getSelectedItem());
            String valorEntradaTransicao = null;
            if (comboEntradaTransicao.getSelectedIndex() > 0) {
                valorEntradaTransicao = comboEntradaTransicao.getSelectedItem().toString();
            }
            String valorAtualPilhaTransicao = comboValorPilhaTransicao.getSelectedItem().toString();
            String valorEntradaPilhaTransicao = null;
            if (comboValorEntradaPilhaTransicao.getSelectedIndex() > 0){
                valorEntradaPilhaTransicao = comboValorEntradaPilhaTransicao.getSelectedItem().toString();
            }
            
            Transicao transicao = new Transicao();
            transicao.setEntrada(valorEntradaTransicao);
            transicao.setEstadoAtual(estadoAtualTransicao);
            transicao.setProximoEstado(proximoEstadoTransicao);
            transicao.setValorEntradaPilha(valorEntradaPilhaTransicao);
            transicao.setValorPilha(valorAtualPilhaTransicao);
            
            modelTransicoes.addRow(transicao);
            
            comboEstadoAtualTransicao.setSelectedIndex(0);
            comboEntradaTransicao.setSelectedIndex(0);
            comboValorPilhaTransicao.setSelectedIndex(0);
            comboValorEntradaPilhaTransicao.setSelectedIndex(0);
            comboProximoEstadoTransicao.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_btnAdicionarTransicaoActionPerformed

    private void btnRemoverTransicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverTransicaoActionPerformed
        // TODO add your handling code here:
        if (tabelaTransicoes.getSelectedRow() != -1){
            modelTransicoes.removeRow(tabelaTransicoes.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoverTransicaoActionPerformed

    private void btnProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessarActionPerformed
        // TODO add your handling code here:
        boolean ehValido = true;
        if (comboEstadoInicial.getSelectedIndex() < 1){
            JOptionPane.showMessageDialog(null, "Deve ser informado um estado inicial");
            ehValido = false;
        }
        if (comboSimboloInicialPilha.getSelectedIndex() < 1){
            JOptionPane.showMessageDialog(null, "Deve ser informado um símbolo inicial para a pilha");
            ehValido = false;
        }
        if (ehValido){
            String ei = comboEstadoInicial.getSelectedItem().toString();
            String sip = comboSimboloInicialPilha.getSelectedItem().toString();
            automato.setEstadoInicial(automato.buscarEstadoPorNome(ei));
            automato.setEstadoAtual(automato.getEstadoInicial());
            automato.setSimboloInicialPilha(sip);
            automato.setPilha(new LinkedList<>());
            automato.addValorPilha(automato.getSimboloInicialPilha());
            String palavra = textPalavra.getText();
            String analise = "";
            if (palavra != null){
                String[] palavraQuebrada = palavra.trim().split("");
                List<Transicao> transicoes = null;
                if (palavraQuebrada.length > 0){
                    if (!palavraQuebrada[0].isEmpty()){
                        boolean palavraValida = false;
                        for (String string : palavraQuebrada) {
                            if (automato.buscarAlfabetoPorValor(string) != null){
                                transicoes = modelTransicoes.getListaTransicaoPorEstado(automato.getEstadoAtual());
                                palavraValida = false;
                                for (Transicao transicao : transicoes){
                                    if (string.equalsIgnoreCase(transicao.getEntrada())){
                                        if (transicao.getValorPilha().equals(automato.topoPilha())){
                                            analise += automato.getEstadoAtual().getNome()+
                                                    "-{"+(transicao.getEntrada() != null ? transicao.getEntrada() : "E")+
                                                    ","+transicao.getValorPilha()+","+
                                                    (transicao.getValorEntradaPilha() != null ? transicao.getValorEntradaPilha()+automato.topoPilha() : "E")+
                                                    "}\n";
                                            if (transicao.getValorEntradaPilha() == null){
                                                if (automato.posicaoTopo() > 1){
                                                    automato.removerTopo();                                                    
                                                }else{
                                                    palavraValida = true;
                                                    break;
                                                }
                                            }else{
                                                automato.addValorPilha(transicao.getValorEntradaPilha());                                                
                                            }
                                            automato.setEstadoAtual(transicao.getProximoEstado());
                                            palavraValida = true;
                                            break;
                                        }
                                    }
                                }
                                if (!palavraValida){
                                    break;
                                }                                
                            }else{
                                analise += string+" - Símbolo inválido";
                                palavraValida = false;
                                break;
                            }
                        }
                        if (!palavraValida){
                            areaAnalise.setText(analise);
                            labelResultado.setForeground(Color.RED);
                            labelResultado.setText("Inválido");
                        }else{
                            if (automato.getEstadoAtual().isEhFinal()){
                                areaAnalise.setText(analise);
                                if (automato.topoPilha().equals(automato.getSimboloInicialPilha())){
                                    labelResultado.setForeground(Color.GREEN);
                                    labelResultado.setText("Válido");
                                }else{
                                    labelResultado.setForeground(Color.RED);
                                    labelResultado.setText("Inválido");
                                }
                            }else{
                                transicoes = modelTransicoes.getListaTransicaoPorEstado(automato.getEstadoAtual());
                                if (transicoes != null){
                                    for (Transicao transicao : transicoes) {
                                        if (transicao.getEntrada() == null 
                                                && transicao.getValorEntradaPilha() == null
                                                && transicao.getValorPilha().equals(automato.topoPilha())){
                                            analise += automato.getEstadoAtual().getNome()+
                                                    "-{"+(transicao.getEntrada() != null ? transicao.getEntrada() : "E")+
                                                    ","+transicao.getValorPilha()+","+
                                                    (transicao.getValorEntradaPilha() != null ? transicao.getValorEntradaPilha()+automato.topoPilha() : "E")+
                                                    "}\n";
                                            automato.setEstadoAtual(transicao.getProximoEstado());
                                            if (automato.posicaoTopo() > 1){
                                                automato.removerTopo();                                                    
                                            }
                                            break;
                                        }
                                    }
                                    areaAnalise.setText(analise);
                                    if (automato.getEstadoAtual().isEhFinal()){
                                        if (automato.topoPilha().equals(automato.getSimboloInicialPilha())){
                                            labelResultado.setForeground(Color.GREEN);
                                            labelResultado.setText("Válido");
                                        }else{
                                            labelResultado.setForeground(Color.RED);
                                            labelResultado.setText("Inválido");
                                        }
                                    }else{
                                        labelResultado.setForeground(Color.RED);
                                        labelResultado.setText("Inválido");
                                    }
                                }else{
                                    areaAnalise.setText(analise);
                                    labelResultado.setForeground(Color.RED);
                                    labelResultado.setText("Inválido");
                                }
                            }
                        }
                    }else{
                        transicoes = modelTransicoes.getListaTransicaoPorEstado(automato.getEstadoAtual());
                        if (transicoes != null){
                            for (Transicao transicao : transicoes) {
                                if (transicao.getEntrada() == null 
                                        && transicao.getValorEntradaPilha() == null
                                        && transicao.getValorPilha().equals(automato.getSimboloInicialPilha())){
                                    analise += automato.getEstadoAtual().getNome()+
                                                    "-{"+(transicao.getEntrada() != null ? transicao.getEntrada() : "E")+
                                                    ","+transicao.getValorPilha()+","+
                                                    (transicao.getValorEntradaPilha() != null ? transicao.getValorEntradaPilha()+automato.topoPilha() : "E")+
                                                    "}\n";
                                    automato.setEstadoAtual(transicao.getProximoEstado());
                                    if (automato.posicaoTopo() > 1){
                                        automato.removerTopo();                                                    
                                    }
                                    break;
                                }
                            }
                            areaAnalise.setText(analise);
                            if (automato.getEstadoAtual().isEhFinal()){
                                if (automato.topoPilha().equals(automato.getSimboloInicialPilha())){
                                    labelResultado.setForeground(Color.GREEN);
                                    labelResultado.setText("Válido");
                                }else{
                                    labelResultado.setForeground(Color.RED);
                                    labelResultado.setText("Inválido");
                                }
                            }else{
                                labelResultado.setForeground(Color.RED);
                                labelResultado.setText("Inválido");
                            }
                        }else{
                            areaAnalise.setText(analise);
                            if (automato.getEstadoAtual().isEhFinal()){
                                if (automato.topoPilha().equals(automato.getSimboloInicialPilha())){
                                    labelResultado.setForeground(Color.GREEN);
                                    labelResultado.setText("Válido");
                                }else{
                                    labelResultado.setForeground(Color.RED);
                                    labelResultado.setText("Inválido");
                                }
                            }else{
                                labelResultado.setForeground(Color.RED);
                                labelResultado.setText("Inválido");
                            }
                        }
                    }
                }else{
                    transicoes = modelTransicoes.getListaTransicaoPorEstado(automato.getEstadoAtual());
                    if (transicoes != null){
                        for (Transicao transicao : transicoes) {
                            if (transicao.getEntrada() == null 
                                    && transicao.getValorEntradaPilha() == null
                                    && transicao.getValorPilha().equals(automato.getSimboloInicialPilha())){
                                analise += automato.getEstadoAtual().getNome()+
                                                    "-{"+(transicao.getEntrada() != null ? transicao.getEntrada() : "E")+
                                                    ","+transicao.getValorPilha()+","+
                                                    (transicao.getValorEntradaPilha() != null ? transicao.getValorEntradaPilha()+automato.topoPilha() : "E")+
                                                    "}\n";
                                automato.setEstadoAtual(transicao.getProximoEstado());
                                break;
                            }
                        }
                        areaAnalise.setText(analise);
                        if (automato.getEstadoAtual().isEhFinal()){
                            if (automato.topoPilha().equals(automato.getSimboloInicialPilha())){
                                labelResultado.setForeground(Color.GREEN);
                                labelResultado.setText("Válido");
                            }else{
                                labelResultado.setForeground(Color.RED);
                                labelResultado.setText("Inválido");
                            }
                        }else{
                            labelResultado.setForeground(Color.RED);
                            labelResultado.setText("Inválido");
                        }
                    }else{
                        areaAnalise.setText(analise);
                        if (automato.getEstadoAtual().isEhFinal()){
                            if (automato.topoPilha().equals(automato.getSimboloInicialPilha())){
                                labelResultado.setForeground(Color.GREEN);
                                labelResultado.setText("Válido");
                            }else{
                                labelResultado.setForeground(Color.RED);
                                labelResultado.setText("Inválido");
                            }
                        }else{
                            labelResultado.setForeground(Color.RED);
                            labelResultado.setText("Inválido");
                        }
                    }
                }
            }        
        }
    }//GEN-LAST:event_btnProcessarActionPerformed

    private void comboEstadoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEstadoInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaAnalise;
    private javax.swing.JButton btnAdicionarEstado;
    private javax.swing.JButton btnAdicionarTransicao;
    private javax.swing.JButton btnProcessar;
    private javax.swing.JButton btnRemoverAlfabeto;
    private javax.swing.JButton btnRemoverEstado;
    private javax.swing.JButton btnRemoverSimboloPilha;
    private javax.swing.JButton btnRemoverTransicao;
    private javax.swing.JButton btnSalvarAlfabeto;
    private javax.swing.JButton btnSalvarSimboloPilha;
    private javax.swing.JCheckBox checkEhFinal;
    private javax.swing.JComboBox<String> comboEntradaTransicao;
    private javax.swing.JComboBox<String> comboEstadoAtualTransicao;
    private javax.swing.JComboBox<String> comboEstadoInicial;
    private javax.swing.JComboBox<String> comboProximoEstadoTransicao;
    private javax.swing.JComboBox<String> comboSimboloInicialPilha;
    private javax.swing.JComboBox<String> comboValorEntradaPilhaTransicao;
    private javax.swing.JComboBox<String> comboValorPilhaTransicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTable tabelaAlfabeto;
    private javax.swing.JTable tabelaEstados;
    private javax.swing.JTable tabelaSimbolosPilha;
    private javax.swing.JTable tabelaTransicoes;
    private javax.swing.JTextField textNomeEstado;
    private javax.swing.JTextField textPalavra;
    private javax.swing.JTextField textValorAlfabeto;
    private javax.swing.JTextField txtSimboloPilha;
    // End of variables declaration//GEN-END:variables
}
